# Generated by Django 4.0.4 on 2022-07-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('iso3', models.CharField(blank=True, max_length=45, null=True)),
                ('iso2', models.CharField(blank=True, max_length=45, null=True)),
                ('numeric_code', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=45, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('tld', models.CharField(blank=True, max_length=45, null=True)),
                ('native', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_region', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('emoji', models.CharField(blank=True, max_length=200, null=True)),
                ('emojiU', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('translations_id', models.AutoField(primary_key=True, serialize=False)),
                ('kr', models.CharField(blank=True, max_length=45, null=True)),
                ('br', models.CharField(blank=True, max_length=45, null=True)),
                ('pt', models.CharField(blank=True, max_length=45, null=True)),
                ('nl', models.CharField(blank=True, max_length=45, null=True)),
                ('hr', models.CharField(blank=True, max_length=45, null=True)),
                ('fa', models.CharField(blank=True, max_length=45, null=True)),
                ('de', models.CharField(blank=True, max_length=45, null=True)),
                ('es', models.CharField(blank=True, max_length=45, null=True)),
                ('fr', models.CharField(blank=True, max_length=45, null=True)),
                ('ja', models.CharField(blank=True, max_length=45, null=True)),
                ('it', models.CharField(blank=True, max_length=45, null=True)),
                ('cn', models.CharField(blank=True, max_length=45, null=True)),
                ('tr', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CountryStateDB.country')),
            ],
        ),
        migrations.CreateModel(
            name='TimeZones',
            fields=[
                ('time_zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('gmt_offset', models.CharField(blank=True, max_length=200, null=True)),
                ('gmt_offset_name', models.CharField(blank=True, max_length=200, null=True)),
                ('abreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('tz_name', models.CharField(blank=True, max_length=200, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CountryStateDB.country')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CountryStateDB.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CountryStateDB.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CountryStateDB.state')),
            ],
        ),
    ]
